### ISSUE TITLE
  @backstage/core-components 0.14

### ISSUE THREAD

**Issue by michaelsync** [PagerDuty/backstage-plugin#102]
Hi,

The code in the main branch and next branch are using   @backstage/core-components 0.13. Any plan to use  @backstage/core-components 0.14? The cli version check is picking up on this and we can't remove the 0.13 because pager plugin is still using it. 

Thanks,
MS

**Comment by t1agob** [comment]
Hi @michaelsync! 
I can definitely look into doing this in the short term. Thanks!

**Comment by t1agob** [comment]
Backstage dependencies have been upgraded to the latest version. This is now merger into `next` branch and will be merged to `main` soon and released under version 0.12.1.

**Comment by t1agob** [comment]
Closing as this is now fixed in version [0.12.1](https://github.com/PagerDuty/backstage-plugin/releases/tag/0.12.1).
