### ISSUE TITLE
Reuse previous inputs when creating new incident with empty description

### ISSUE THREAD

**Issue by MaxineGS** [PagerDuty/backstage-plugin#103]
**Describe the bug**
When i create incident with pagerduty backstage plugin, the first time i create incident with description "Test Incident 1" and click trigger button. Then i open create incident again, the trigger button should be disable with empty description. But I can still click `Trigger Incident` button, and will create a incident same with previous one.

**To Reproduce**
1. Trigger PagerDuty incident via Backstage with description not empty.
2. Trigger PagerDuty incident again without description (empty description), a new incident will be created but the description will be the same as the previous one. 

**Expected behavior**
Without description, the trigger button should be disabled. (maybe clear description text field each time the create incident modal is closed)

**Screenshots**
<img width="965" alt="Screenshot 2024-06-11 at 13 46 09" src="https://github.com/PagerDuty/backstage-plugin/assets/162249507/694d73be-8f38-4a68-9689-5a4426bbc474">

**Comment by t1agob** [comment]
I was able to replicate the issue. Working on it now!

**Comment by t1agob** [comment]
This bug is now fixed. Please upgrade to [0.12.2](https://github.com/PagerDuty/backstage-plugin/releases/tag/0.12.2).
