### ISSUE TITLE
OAuth Authentication for PagerDuty Fails with "Missing or Invalid PagerDuty Token" Error

### ISSUE THREAD

**Issue by RP-flaviojunior** [PagerDuty/backstage-plugin#104]
**Describe the bug**
The OAuth authentication method for PagerDuty is not working. When attempting to authenticate, the following error messages are logged:

```shell
[1] 2024-06-12T13:45:55.611Z pagerduty warn No PagerDuty API token found in config file. Trying OAuth token instead...
[1] 2024-06-12T13:45:56.512Z rootHttpRouter info ::1 - - [12/Jun/2024:13:45:56 +0000] "POST /api/permission/authorize HTTP/1.1" 200 74 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" type=incomingRequest
[1] 2024-06-12T13:45:56.513Z rootHttpRouter info ::1 - - [12/Jun/2024:13:45:56 +0000] "POST /api/catalog/entities/by-refs/ HTTP/1.1" 200 822 "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" type=incomingRequest
[1] 2024-06-12T13:45:56.582Z pagerduty error Unable to retrieve valid PagerDuty AUTH configuration from config file: Error: Failed to retrieve valid token. Bad Request - Invalid arguments provided.
```

In the console, the following message appears:

```shell
Missing or invalid PagerDuty Token
```

**To Reproduce**
1. Configure the Backstage app with the following app-config.yaml settings:
```yaml
pagerDuty:
  oauth:
    clientId: ${PD_CLIENT_ID}
    clientSecret: ${PD_CLIENT_SECRET}
    subDomain: ${PD_ACCOUNT_SUBDOMAIN}
    region: ${PD_ACCOUNT_REGION}
```
2. Start the Backstage application.
3. Attempt to authenticate with PagerDuty using OAuth.
4. Observe the error messages in the logs and console.

**Expected behavior**
The OAuth authentication should successfully retrieve a valid token and authenticate with PagerDuty without errors.

**Screenshots**
![Screenshot 2024-06-12 at 10 57 30](https://github.com/PagerDuty/backstage-plugin/assets/119867244/4f9c7c28-f925-47cd-a62c-8d416b03360c)

**Desktop (please complete the following information):**
 - OS: Mac OS X 14.0
 - Browser: Chrome
 - Version: 125.0.6422.142

**Additional context**
The issue appears to be related to the inability to retrieve a valid token from PagerDuty using the provided OAuth credentials.

**Comment by t1agob** [comment]
Hello @RP-flaviojunior! Thanks for reporting this and congrats on opening your first issue with us.

I've been trying to reproduce this error but I'm unable to. Can you double check if the environment variables you are passing to your `app-config.yaml` file are actually present and correct? Thanks in advance!

**Comment by t1agob** [comment]
@RP-flaviojunior have you been able to overcome this issue? Or are you still experiencing it?

**Comment by chauvm** [comment]
Hi @t1agob ! I'm getting the same issue so I'm going to hijack this thread, please let me know if I should open a new issue.

Here's what I have done:
1. Follow this [guide](https://pagerduty.github.io/backstage-plugin-docs/getting-started/pagerduty/) to get client ID and secret for a scoped OAuth app
2.  Install the plugin and configure new backend system following the next [step](https://pagerduty.github.io/backstage-plugin-docs/getting-started/pagerduty/)
```
yarn add --cwd packages/app @pagerduty/backstage-plugin
yarn add --cwd packages/backend @pagerduty/backstage-plugin-backend

// add frontend changes to 
// add backend changes to packages/backend/src/index.ts
backend.add(import('@pagerduty/backstage-plugin-backend'));
```

3. Configure authorization in `app-config.yaml`
```
pagerDuty:
  oauth:
    clientId: ${PD_CLIENT_ID}
    clientSecret: ${PD_CLIENT_SECRET}
    subDomain: ${PD_ACCOUNT_SUBDOMAIN}
    region: us
```
I can exec into my Kubernetes pod and confirm that the above environment variables have the expected values.

One thing I'm not sure is `PD_ACCOUNT_SUBDOMAIN`, is it supposed to be `myorg.pagerduty.com` or just `myorg`?

Symptoms: Frontend doesn't show any new PagerDuty compoents, and here's the error I see in the pod:
```
pagerduty warn No PagerDuty accounts configuration found in config file. Reverting to legacy configuration.
pagerduty warn No PagerDuty API token found in config file. Trying OAuth token instead...
pagerduty error Unable to retrieve valid PagerDuty AUTH configuration from config file: Error: Failed to retrieve valid token. Bad Request - Invalid arguments provided.
```

**Comment by t1agob** [comment]
Thanks for adding all these details @chauvm.

For the subdomain you just need `myorg` if your PagerDuty org url is `myorg.pagerduty.com`. Can you give it a go and let me know if you get the same error?

**Comment by chauvm** [comment]
thank you very much! That's indeed the problem. Everything works now!

**Comment by t1agob** [comment]
Thanks for confirming. I have updated the documentation to clearly describe what type of information we are looking for `subDomain`.

I will now close this issue.
