### ISSUE TITLE
Two-way mapping between Backstage service dependencies and PagerDuty

### ISSUE THREAD

**Issue by t1agob** [PagerDuty/backstage-plugin#111]
**Is your feature request related to a problem? Please describe.**
Today we use Backstage as a main source of truth for service dependencies as we sync with multiple providers and therefore leverage Backstage as the default place to go to search for this information. 

**Describe the solution you'd like**
We would like that our dependencies would be mapped to PagerDuty and kept in sync. We don't have service dependency configurations in PagerDuty and therefore we don't take a lot of advantage of PagerDuty's service mapping and status pages. We would like to but it just takes to much effort to do these configurations in multiple places. 

**Describe alternatives you've considered**
We have considered to implement some scripts to sync Backstage and PagerDuty using the PagerDuty REST APIs. But if this feature would be brought into the plugin we would save a lot of time and I believe this is useful for other customers as well.

**Additional context**
This feature was requested by @brianphillips and the Shutterstock team.

**Comment by t1agob** [comment]
Work as started to implement this feature and our current implementation starts with a one-way sync between Backstage and PagerDuty, having Backstage as the primary source.

All users that I interviewed at this point in time use Backstage as their "source of truth" and are looking for solutions to have their service dependencies mapped to external tools (like PagerDuty). 

Our current approach is to extend the Entity Processor to look into existing annotations in each Backstage Entity and create the corresponding service dependencies in PagerDuty automatically. Below are the proposed mappings that we are looking to implement.


Backstage Annotation | PagerDuty equivalent
-- | --
ownedBy | Team
DependsOn | Technical Service
DependencyOf | Technical Service
partOf | Business Service
hasPart | Business Service

We are looking for feedback on this proposed implementation. Feel free to comment directly on this issue.

@brianphillips calling you out on this one 😎

**Comment by t1agob** [comment]
I am rethinking the above approach a little bit to allow two-way sync from day one. Would it be helpful to have a setting in the PagerDuty Advanced Configuration Page to allow users to select their preferred sync behaviour:
1. Backstage is the main source 
2. PagerDuty is the main source
3. Merge dependencies from both sides (this would take dependencies on both sides and make sure they match)

**Would this be an ok approach?**

**Comment by brianphillips** [comment]
@t1agob I think the overall approach is :ok_hand: I do have questions/concerns about how any completely automated approach will handle an existing Backstage<->PagerDuty setup that is currently configured in a non-synchronized fashion. Will all new services be created on the PagerDuty side? How will unmapped Backstage owners be mapped to a new PagerDuty team? What about members of those teams? Will they be synchronized as well?

**Comment by t1agob** [comment]
Got it! I will break this into different features because I don't have enough information on team and user syncing. I need to collect more information on real usage. I'll focus this effort on services exclusively as it was stated in the initial problem we are trying to solve. 

Regarding your first concern, we have a scaffolder action available for user to automatically create services in PagerDuty but is everyone using it? I cannot guarantee. 

This is actually one of the limitations of service dependency sync because we can only sync dependencies for services that are mapped into Backstage entities. So, for it to work, users of the plugin need to either add a `service-id` annotation to their Backstage entities (by using the scaffolder action or not) or use the new Service to Entity Mapping capabilities that we introduced in the latest version.

**Comment by t1agob** [comment]
Closing this issue as it is now possible to sync services between Backstage and PagerDuty. As discussed above, team sync and Business Service integrations will be left for a later stage as it was out of scope of the initial issue and we don't have enough information about their usage on Backstage. **Release 0.15.0** adds support for the following:

Backstage Annotation | PagerDuty equivalent
-- | --
DependsOn | Technical Service
DependencyOf | Technical Service

‼️ **Important:** Due to a Backstage design decision it is not possible to fully overwrite the relations specified in each entity's configuration file. For that reason the option to synchronise strictly from PagerDuty side is not available.
