### ISSUE TITLE
The toggle visibility elements of the  "Show/Hide columns" button on the PagerDutyPage do not work

### ISSUE THREAD

**Issue by alpinweis** [PagerDuty/backstage-plugin#123]
**Describe the bug**
The toggle visibility elements of the  "Show/Hide columns" button on the PagerDutyPage do not seem to work.

**To Reproduce**
Navigate to the PagerDutyPage component, wait for the Page to load, click on the `Show/Hide columns` button on the top right hand side of the table, try to toggle any element of the drop down menu or select the `Hide All` or `Show all`. Nothing works. It's impossible to toggle any element.

**Expected behavior**
The chosen visibility toggle should change to off/on when selected. The `Hide All` and `Show all` buttons should toggle off/on all visibility toggles. The change should result in hiding/showing the respective columns.

**Additional context**
backstage version: 1.29.1
"@pagerduty/backstage-plugin": "0.14.1",
"@pagerduty/backstage-plugin-common": "0.2.0",
"@pagerduty/backstage-plugin-backend": "0.8.2"

<img width="240" alt="pd show hide columns" src="https://github.com/user-attachments/assets/bac90eb3-ad5d-4dc8-bf84-a8a79a0df793">

**Comment by t1agob** [comment]
Closing this issue as it's now fixed on version 0.15.0.
