### ISSUE TITLE
On call engineers are duplicated 

### ISSUE THREAD

**Issue by jcoelho93** [PagerDuty/backstage-plugin#36]
**Describe the bug**

There are 2 issues with the list of on call engineers:
 * It does not identify which engineer is the primary on call responder
 * There are duplicate engineers in the list  

**To Reproduce**
1. Go to a service's page, with an escalation policy with multiple engineers
2. The list of on call engineers will not display the primary on call
3. The list of on call engineers will have some duplicates

**Expected behavior**

* The primary on call engineer should be clearly identified.
* There shouldn't be duplicates, if there are then it should be easy to understand why there are duplicates

**Screenshots**

* David Wallace is the primary on call engineer, but it's not identified as so.
* David Wallace and Jim Halpert are duplicated for some reason

<img width="579" alt="Screenshot 2023-11-08 at 13 27 38" src="https://github.com/PagerDuty/backstage-plugin/assets/16445494/b5cafe12-7d39-44d8-b71f-56e95bc083cd">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version 119

**Comment by t1agob** [comment]
Hi @jcoelho93!
I was able to replicate the issue IF I specify users individually in the escalation policy. If I use a on-call schedule instead I only get the user currently on-call.

Can you please confirm if that is your case as well? Thanks!

**Comment by jcoelho93** [comment]
@t1agob yes, I confirm, we have an escalation policy with multiple levels.

**Comment by t1agob** [comment]
@jcoelho93 this issue has now been resolved and merged into next branch (#38) . It will be merged into main and released by the end of the week November 17.

I have solved the issues you reported and now the plugin only lists oncall users on escalation level 1 and no duplicates will show up. I have also added support for user's profile picture instead of the default dummy avatar icon.
