### ISSUE TITLE
Backend plugin for querying PagerDuty plugin

### ISSUE THREAD

**Issue by jcoelho93** [PagerDuty/backstage-plugin#37]
## Is your feature request related to a problem? Please describe.

As stated in the README of this project `"the PagerDuty plugin requires the /pagerduty proxy endpoint be exposed by the Backstage backend as an unprotected endpoint"`. This raises some security concerns as it leaves the PagerDuty API open to anyone with access to Backstage, without the need to provide any credentials.

## Describe the solution you'd like

Backstage documentation recommend using a backend plugin to mitigate this issue. See [here](https://backstage.io/docs/overview/threat-model/#proxy:~:text=It%20is%20recommended%20that%20you%20instead%20create%20a%20backend%20plugin%20that%20forwards%20individual%20requests%20to%20the%20upstream%20service%20in%20a%20secure%20way)

> Anyone with access to your Backstage deployment will be able to make requests to the upstream service using the injected credentials. It is recommended that you instead create a backend plugin that forwards individual requests to the upstream service in a secure way

* [This page](https://backstage.io/docs/plugins/backend-plugin/) documents the process of developing backend plugins

## Describe alternatives you've considered

A likely easier alternative, but still not as safe, would be to log each request to the PagerDuty API with the user ID of the requester. This would at least give us a place to start to investigate any potential security incidents.

**Comment by t1agob** [comment]
This capability is now merged to main and will be launch on release 0.8.1.
