### ISSUE TITLE
Custom scaffolder action to create PagerDuty service

### ISSUE THREAD

**Issue by t1agob** [PagerDuty/backstage-plugin#41]
**Is your feature request related to a problem? Please describe.**
The problem that I am trying to solve is of new service onboarding, i.e. when a new service gets created, I want to create a new PD service for it based on the PD team provided by user input.

**Describe the solution you'd like**
Create scaffolder action to create a PagerDuty Service from Backstage:
- pagerduty:create:service - which creates a pagerduty service

**Additional context**
Original issue raised by @Alok650 in #35. Broken down into two issues to reduce scope.

**Comment by t1agob** [comment]
@Alok650 This request is now implemented in the latest version of [backend plugin](https://github.com/PagerDuty/backstage-plugin-backend).

To use the custom action in your templates follow the documentation [here](https://pagerduty.github.io/backstage-plugin-docs/advanced/create-service-software-template/).

**Comment by Alok650** [comment]
Thanks @t1agob for taking it up on priority. will try it out and give feedback.
