### ISSUE TITLE
Users without AIOps or Event Intelligence license getting 403 on "Change Events" tab

### ISSUE THREAD

**Issue by yoramshai** [PagerDuty/backstage-plugin#63]
**Describe the bug**
Getting 403 error on the Change Events tab 
![image](https://github.com/PagerDuty/backstage-plugin-common/assets/11707803/862a5fb4-d620-41c8-ae04-d80661ddecc5)

**To Reproduce**
1. Use basic user API token 
2. Navigate to the PD section on the overview page.
2. Click on 'Change Events'

**Expected behavior**
Hide this tab or have a proper message rather than an error.

**Comment by t1agob** [comment]
This issue is fixed and release on version 0.8.3. Thanks for your contribution @yoramshai.
