### ISSUE TITLE
New release `0.8.1` breaks use of different PagerDuty API host

### ISSUE THREAD

**Issue by pcgqueiroz** [PagerDuty/backstage-plugin#74]
**Describe the bug**
The new release `0.8.1` that deprecates the proxy configuration in favor of using a backend plugin to make calls to the PagerDuty REST API does not offer the possibility to change the server base URL. Calls to the european server https://api.eu.pagerduty.com are not possible anymore.

**Expected behavior**
The possibility in the configuration to change the API server.

**Comment by t1agob** [comment]
Thanks for reporting this @pcgqueiroz. 

While the plugin continues to work it introduces additional latency if your PagerDuty instance is running in Europe for sure. I'll look into this with high priority and add support for an override like we already have for the events url.

**Comment by t1agob** [comment]
@pcgqueiroz This should be fixed now. Please upgrade to the latest version of the packages and follow the docs on how to configure/override the base REST API url.

**latest versions**
- Frontend ([0.9.2](https://pagerduty.github.io/release-notes/frontend/#092))
- Backend ([0.4.3](https://pagerduty.github.io/release-notes/backend/#043))
- Common ([0.1.1](https://pagerduty.github.io/release-notes/common/#011))
