### ISSUE TITLE
Small sized PagerDutyCard component

### ISSUE THREAD

**Issue by t1agob** [PagerDuty/backstage-plugin#86]
**Is your feature request related to a problem? Please describe.**
Our Entity page has multiple tabs and we reserve the first one to smaller widgets to provide relevant and quick information to users. We then have specific tab for `Operations` where we would like to keep the existing card.

**Describe the solution you'd like**
I would like to have a smaller card that shows the status of the service, the oncall engineer, service standards and eventually some statistics. Details on incidents are not necessary, we have the other PagerDuty card for that.

**Describe alternatives you've considered**
We are considering building an internal-only custom component to expose only the information we need.

**Comment by milenkotomic** [comment]
Hi @t1agob, is this feature in active development? In our company we build a small card to our overview page that includes the status of the service and the on-call engineer, and would be happy to shared it

**Comment by t1agob** [comment]
Hello @milenkotomic! 
This feature is not being developed yet so if you want to contribute it to the community that would be great! I would start by looking into our [contribution guidelines](https://github.com/PagerDuty/backstage-plugin/blob/main/CONTRIBUTING.md) and create a PR.

I can work with you on reviewing this and making sure it's aligned with the other components from a UI/UX and API usage perspective.

**Comment by milenkotomic** [comment]
Hi @t1agob! 
I can't push to create a PR, I'm getting error 403, can you help me with that?
Thanks!

**Comment by t1agob** [comment]
You should be able to fork the project, create your own branch and create a PR to `next`. Is this the process you followed?

**Comment by milenkotomic** [comment]
No, I misread the contributing guidelines, I was trying to push a branch straight to this repo, sorry.

**Comment by t1agob** [comment]
After gathering feedback from a few other folks I came up with a slight change to your PR. @milenkotomic What do you think of this?

👇 This shows the card with collapsable panels for insights and on-call.

![image](https://github.com/PagerDuty/backstage-plugin/assets/2689939/7d8e4d17-5d05-4a72-8850-ba6082f57a7c)

👇 This one shows the same panel with the panels expanded. 

![image](https://github.com/PagerDuty/backstage-plugin/assets/2689939/8bdf812e-e0de-47d6-812a-f924c5075a43)

You can still choose to disable booth tabs. Does that work?

**Comment by milenkotomic** [comment]
Hi @t1agob!
Yes, it looks great, I'll try to make those changes as soon a I can

**Comment by t1agob** [comment]
no need to @milenkotomic. just pushed the changes to #95. 

If you could pull the changes and try it out yourself and see if it works as expected I would appreciate. I can then merge the PR.

**Comment by milenkotomic** [comment]
It works as expected, I tried the different combinations of options and all of them worked perfect.
There is a bit a commented code that should be removed in my opinion before the merge, but besides that everything is good @t1agob.

**Comment by t1agob** [comment]
Thanks for catching that. I'll clean it up before merging. 

Thank you for your contribution. It really helped unblock this one.

**Comment by t1agob** [comment]
This is now merged and available as part of [@pagerduty/backstage-plugin](https://www.npmjs.com/package/@pagerduty/backstage-plugin/v/0.12.0) 0.12.0 version.
