### ISSUE TITLE
Updating to 0.10 or newer can't find the service

### ISSUE THREAD

**Issue by jcarres-mdsol** [PagerDuty/backstage-plugin#92]
**Describe the bug**

After updating from 0.9.3 to newer versions (0.10 , 0.11) the widget can not find the service anymore.

In 0.9.3 I see these calls in the backend

GET /api/pagerduty/services/<id>
GET /api/pagerduty/oncall-users?escalation_policy_ids[]=<id>
GET /api/pagerduty/services/<id>/incidents

They return 304 and work

With 0.10 I see

GET /api/pagerduty/services/<id> 304
GET /api/pagerduty/services/<id>/standards 404

In the UI the widget says the service was not found. But I do not think so, I think it is picking the 404 of the standards. The standards were not found but well, I do not care about standards anyways.

**Comment by hballangan-mdsol** [comment]
@t1agob 
1. The latest version 
2. Api token
3.
app config contains:
```
pagerDuty:
  apiToken: ${PAGERDUTY_TOKEN}
```

Each component factbook has `pagerduty.com/service-id: PPPPPP` under annotations

**Comment by t1agob** [comment]
Thanks @hballangan-mdsol! Which version of `@pagerduty/backstage-plugin-backend` and `@pagerduty/backstage-plugin-common` are you using for your backend?

I just want to make sure I am using the same versions while trying to replicate the issue.

**Comment by t1agob** [comment]
Perfect! Totally agree with your feedback. Our recommendation is to always upgrade all packages to the latest version if possible.

I'll make it clear on the documentation for the next releases **if there are specific dependencies between frontend and backend components**.
