### ISSUE TITLE
Support for multiple PagerDuty accounts

### ISSUE THREAD

**Issue by harikennedy** [PagerDuty/backstage-plugin#96]
Currently, the plugin is limited to using a single API key. This is restrictive for scenarios where mulitple PagerDuty integrations are necessary.

**Comment by t1agob** [comment]
Hello @harikennedy! 
Can you elaborate more on a scenario where you would need to use multiple API Keys?

**Comment by harikennedy** [comment]
In our setup, we're dealing with two different PagerDuty instances because our teams operate independently and need to manage their incidents separately. Our Backstage setup currently can't handle two instances since the plugin supports only a single API key. We're looking for a way to route to the correct PagerDuty instance based on the service context within Backstage. Could we have support for multiple API keys to accommodate this? 

Reference (Auth): 
https://github.com/PagerDuty/backstage-plugin-backend/blob/2f52b41cae9fa54b3f741170e6e977f076e88a6b/src/auth/auth.ts

**Comment by t1agob** [comment]
Got it! This is not the standard approach as most customers have a single account approach I believe. 

I'll review this one. It's not an easy task to perform without hindering the config experience. It will probably require changes to the app config and the service metadata itself. Give me a few days to review this one in more detail and get back to you.

**Comment by martina-equinix** [comment]
Hi @t1agob , I have a similar use case. I have two separate pagerduty accounts (each with their own subdomain and credentials). This can be a typical case when there is an acquisition for example, and the company ends up with at least two PD accounts for a period of time (which can be years even).

**Comment by t1agob** [comment]
@harikennedy @martina-equinix This feature is now available on the latest version (0.14.0). Feel free to try it and provide feedback.

Follow [these](https://pagerduty.github.io/backstage-plugin-docs/getting-started/backstage/#multiple-pagerduty-accounts) in order to set it up.
